# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 14:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelForceImportJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation Time')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentage')),
                ('state', models.IntegerField(choices=[(0, '\u7b49\u5f85'), (1, '\u6210\u529f'), (2, '\u5931\u8d25')], db_index=True, default=0, verbose_name='State')),
                ('input_file', models.FileField(upload_to='parcel_force_imports/%Y/%m/%d', verbose_name='Import File')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='Num of Pages')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_force_import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelForceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Reference Number')),
                ('receiver_name', models.CharField(db_index=True, max_length=32, verbose_name='Receiver Name')),
                ('receiver_phone', models.CharField(db_index=True, max_length=32, verbose_name='Receiver Name')),
                ('dispatch_date', models.DateTimeField(verbose_name='Dispatch Date')),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='track_order.ParcelForceImportJob')),
            ],
        ),
    ]
