# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import track_order.validators


class Migration(migrations.Migration):

    dependencies = [
        ('track_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelforceimportjob',
            name='filename',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Input File Name'),
        ),
        migrations.AlterField(
            model_name='parcelforceimportjob',
            name='input_file',
            field=models.FileField(upload_to='parcel_force_imports/%Y/%m/%d', validators=[track_order.validators.validate_file_extension], verbose_name='Import File'),
        ),
    ]
