# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_order', '0002_auto_20170215_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelforceimportjob',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Percentage'),
        ),
    ]
