# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-05 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import track_order.validators


class Migration(migrations.Migration):

    dependencies = [
        ('track_order', '0003_auto_20170215_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelforceimportjob',
            name='input_file',
            field=models.FileField(upload_to='uploads/parcel_force_imports/%Y/%m/%d', validators=[track_order.validators.validate_file_extension], verbose_name='Import File'),
        ),
    ]
