# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-06 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track_order', '0004_auto_20170505_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=128, unique=True)),
                ('status', models.IntegerField(db_index=True, default=0)),
                ('route', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('creation_time', models.DateTimeField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('landed_time', models.DateTimeField(blank=True, null=True)),
                ('custom_clearance_time', models.DateTimeField(blank=True, null=True)),
                ('agent_query_code', models.IntegerField(blank=True, db_index=True, null=True)),
                ('agent_query_time', models.DateTimeField(blank=True, null=True)),
                ('agent_query_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingRecordItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('detail', models.TextField()),
                ('shipping_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='track_order.ShippingRecord')),
            ],
        ),
    ]
