# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-06 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track_order', '0006_shippingrecord_agent_query_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingrecorditem',
            name='shipping_record',
        ),
        migrations.RemoveField(
            model_name='shippingrecord',
            name='agent_query_code',
        ),
        migrations.DeleteModel(
            name='ShippingRecordItem',
        ),
    ]
