# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-03 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track_order', '0008_shippingrecord_agent_query_fault_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelforceorder',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='track_order.ParcelForceImportJob'),
        ),
        migrations.AlterField(
            model_name='parcelforceorder',
            name='receiver_phone',
            field=models.CharField(db_index=True, max_length=32, verbose_name='Receiver Phone'),
        ),
    ]
