# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-14 19:54
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_no', models.CharField(db_index=True, max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order_api.Package')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_api.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='request',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_api_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.AddField(
            model_name='package',
            name='items',
            field=models.ManyToManyField(through='order_api.PackageItem', to='order_api.Product'),
        ),
        migrations.AddField(
            model_name='package',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_api.Request'),
        ),
    ]
