# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-14 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0004_auto_20170714_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='order_api.Request'),
        ),
        migrations.AlterField(
            model_name='package',
            name='tracking_no',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
