# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-15 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0006_auto_20170714_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='last_retry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
