# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-15 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0007_request_last_retry'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='internal_name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
