# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-15 17:08
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import order_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0009_auto_20170715_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='waybill_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/jie/work/django/projects/courier/waybill_storage'), upload_to=order_api.models.waybill_upload_to),
        ),
    ]
