# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-15 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0010_package_waybill_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='tracking_no',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
