# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-16 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0012_profile_api_test_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='test_mode',
            field=models.BooleanField(default=False),
        ),
    ]
