# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-04 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0017_auto_20170804_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
