# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-04 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0018_auto_20170804_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_api.Route'),
        ),
    ]
