# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-29 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0019_auto_20190804_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='external_package_no',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='external_order_no',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
