# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_order', '0002_auto_20170210_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierbatch',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rate per Package'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courierbatch',
            name='system',
            field=models.CharField(choices=[('yunda', '\u97f5\u8fbe\u7ebf'), ('postal', '\u90ae\u653f\u7ebf')], db_index=True, default='postal', max_length=32, verbose_name='System Name'),
            preserve_default=False,
        ),
    ]
