# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_order', '0003_auto_20170210_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierbatch',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Credit'),
        ),
        migrations.AddField(
            model_name='courierbatch',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='courierbatch',
            name='state',
            field=models.IntegerField(db_index=True, default=0, verbose_name='State'),
        ),
    ]
