# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-29 18:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issue_order', '0009_auto_20170831_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('jixun', '\u5409\u8bafCC\u7ebf'), ('postal', '\u90ae\u653fBC\u7ebf'), ('yunda', '\u97f5\u8fbeCC\u7ebf')], db_index=True, max_length=32, verbose_name='\u7ebf\u8def\u540d\u79f0')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=64)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue_order.CourierOrder')),
            ],
        ),
        migrations.AlterField(
            model_name='courierbatch',
            name='system',
            field=models.CharField(choices=[('jixun', '\u5409\u8bafCC\u7ebf'), ('postal', '\u90ae\u653fBC\u7ebf'), ('yunda', '\u97f5\u8fbeCC\u7ebf')], db_index=True, max_length=32, verbose_name='System Name'),
        ),
        migrations.AlterField(
            model_name='courierrate',
            name='system',
            field=models.CharField(choices=[('jixun', '\u5409\u8bafCC\u7ebf'), ('postal', '\u90ae\u653fBC\u7ebf'), ('yunda', '\u97f5\u8fbeCC\u7ebf')], db_index=True, max_length=32, verbose_name='System Name'),
        ),
        migrations.AlterField(
            model_name='groupprice',
            name='system',
            field=models.CharField(choices=[('jixun', '\u5409\u8bafCC\u7ebf'), ('postal', '\u90ae\u653fBC\u7ebf'), ('yunda', '\u97f5\u8fbeCC\u7ebf')], db_index=True, max_length=32, verbose_name='\u7ebf\u8def'),
        ),
        migrations.AddField(
            model_name='item',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue_order.Package'),
        ),
    ]
