# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-10 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue_order', '0010_auto_20180429_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_template', models.BooleanField(default=False)),
                ('country', models.CharField(choices=[('GB', '\u82f1\u56fd'), ('CN', '\u4e2d\u56fd')], max_length=32)),
                ('post_code', models.CharField(max_length=32)),
                ('contact_name', models.CharField(max_length=64)),
                ('address_line_1', models.CharField(max_length=64)),
                ('address_line_2', models.CharField(blank=True, max_length=64, null=True)),
                ('province', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(max_length=32)),
                ('district', models.CharField(blank=True, max_length=32, null=True)),
                ('contact_number', models.CharField(max_length=32)),
                ('id_number', models.CharField(blank=True, max_length=32, null=True)),
                ('alias', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='package',
            name='receiver_name',
        ),
        migrations.AddField(
            model_name='item',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='package',
            name='receiver_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='issue_order.Address'),
        ),
        migrations.AddField(
            model_name='package',
            name='sender_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='issue_order.Address'),
        ),
    ]
