# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-16 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue_order', '0018_auto_20180828_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pickup_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='issue_order.Address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pickup_option',
            field=models.CharField(choices=[('self_serve', '\u81ea\u9001\u66fc\u57ce\u4ed3\u5e93'), ('pickup_required', '\u4e0a\u95e8\u53d6\u4ef6')], default='self_serve', max_length=64),
        ),
    ]
