# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-03 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_order', '0019_auto_20180916_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierbatch',
            name='system',
            field=models.CharField(choices=[('jixun', '\u5409\u8bafCC\u7ebf'), ('postal', '\u90ae\u653fBC\u7ebf'), ('yunda', '\u97f5\u8fbeCC\u7ebf'), ('heshan', '\u9e64\u5c71CC\u7ebf')], db_index=True, max_length=32, verbose_name='System Name'),
        ),
        migrations.AlterField(
            model_name='courierrate',
            name='system',
            field=models.CharField(choices=[('jixun', '\u5409\u8bafCC\u7ebf'), ('postal', '\u90ae\u653fBC\u7ebf'), ('yunda', '\u97f5\u8fbeCC\u7ebf'), ('heshan', '\u9e64\u5c71CC\u7ebf')], db_index=True, max_length=32, verbose_name='System Name'),
        ),
        migrations.AlterField(
            model_name='groupprice',
            name='system',
            field=models.CharField(choices=[('jixun', '\u5409\u8bafCC\u7ebf'), ('postal', '\u90ae\u653fBC\u7ebf'), ('yunda', '\u97f5\u8fbeCC\u7ebf'), ('heshan', '\u9e64\u5c71CC\u7ebf')], db_index=True, max_length=32, verbose_name='\u7ebf\u8def'),
        ),
        migrations.AlterField(
            model_name='route',
            name='system',
            field=models.CharField(choices=[('jixun', '\u5409\u8bafCC\u7ebf'), ('postal', '\u90ae\u653fBC\u7ebf'), ('yunda', '\u97f5\u8fbeCC\u7ebf'), ('heshan', '\u9e64\u5c71CC\u7ebf')], db_index=True, max_length=32),
        ),
    ]
