# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-24 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_order', '0021_auto_20190129_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_system_offline',
            field=models.BooleanField(default=False),
        ),
    ]
