# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-24 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_order', '0022_route_is_system_offline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='is_system_offline',
        ),
        migrations.AddField(
            model_name='route',
            name='is_system_online',
            field=models.BooleanField(default=True),
        ),
    ]
