# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-24 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_order', '0023_auto_20190424_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='is_system_online',
            new_name='is_online',
        ),
    ]
